name: Fetch git tags

runs:
  using: "composite"
  steps:
    - name: Workaround for https://github.com/actions/checkout/issues/290
      shell: bash
      run: git fetch --tags --prune --unshallow --force
