runs:
  using: "composite"
  steps:
    - name: Cache ~/.cabal/store
      uses: actions/cache@v3
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: cabal-v3-${{ runner.os }}-${{ runner.arch }}
