name: Build release (lamdera-community)

on:
  push:
    tags: '*'
    branches: 'release/*'

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
        - name: macOS-ARM64
          runner: [ self-hosted, macOS, ARM64 ]

    name: release-${{ matrix.build.name }}
    runs-on: ${{ matrix.build.runner }}

    steps:
    - name: Configure environment
      run: |
        git config --global core.autocrlf false
    - uses: actions/checkout@v3
    - name: Check platform
      run: |
        uname -m
        arch
        arch -arm64 uname -m
        file ~/runner-setups/elm-format/_work/_tool/ghcup/0.1.19.0/arm64/ghcup
    - name: Workaround for https://github.com/actions/checkout/issues/290
      run: git fetch --tags --prune --unshallow --force
    - name: Check ghcup cache
      run: |
        find ~/.ghcup -type d
    # - uses: haskell/actions/setup@v2
    #   name: Setup Haskell
    #   id: setup-haskell
    #   with:
    #     ghc-version: 9.2.5
    - name: Setup Haskell
      run: |
        curl -o ghcup https://downloads.haskell.org/~ghcup/0.1.19.0/aarch64-apple-darwin-ghcup-0.1.19.0
        chmod 0555 ./ghcup
        file ./ghcup
        export GHCUP_USE_XDG_DIRS=1
        ./ghcup list
        ./ghcup unset ghc || true
        ./ghcup install ghc 9.2.5
        ./ghcup set ghc 9.2.5
        ./ghcup install cabal recommended
    - name: Verify Haskell version
      run: |
        cabal --version
        ghc --version
        [[ $(ghc --numeric-version) == 9.2.5 ]]
        file "$(which cabal)"
        file "$(which ghc)"
    - uses: actions/cache@v3
      name: Cache cabal-release-v1-${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: cabal-release-v1-${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}
    - run: cabal v2-update
    - run: ./build.sh -- dist-dependencies
    - run: ./build.sh -- dist
    - uses: actions/upload-artifact@v3
      with:
        name: elm-format-${{ github.sha }}-${{ runner.os }}
        path: dist/
    - name: Show ghcup log
      if: always()
      run: (find ~/.ghcup/logs -print0 | xargs -0 cat) || true
