name: Build release

on:
  push:
    tags: '*'
    branches: 'release/*'

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: windows
            runner: windows-latest
            archive-label: Windows
          - name: macOS-x86
            runner: macOS-latest
            archive-label: macOS-x86

    name: release-${{ matrix.build.name }}
    runs-on: ${{ matrix.build.runner }}

    steps:
    - name: Configure environment
      run: |
        git config --global core.autocrlf false
    - name: Configure GPG Key
      run: |
        echo "$GPG_SIGNING_KEY" | base64 --decode > private.key
        gpg --import private.key
        rm private.key
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    - uses: actions/checkout@v3
    - name: Workaround for https://github.com/actions/checkout/issues/290
      run: git fetch --tags --prune --unshallow --force
    - name: Workaround for https://github.com/actions/runner-images/issues/7061
      if: ${{ runner.os == 'Linux' }}
      run: sudo chown -R "$USER" /usr/local/.ghcup
    - uses: haskell/actions/setup@v2
      name: Setup Haskell
      id: setup-haskell
      with:
        ghc-version: 9.2.5
    - name: Verify Haskell version
      run: |
        cabal --version
        ghc --version
        [[ $(ghc --numeric-version) == 9.2.5 ]]
        file "$(which cabal)"
        file "$(which ghc)"
    - uses: actions/cache@v3
      name: Cache ~/.cabal/store
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: cabal-v3-${{ runner.os }}-${{ runner.arch }}
    - run: cabal v2-update
    - run: ./dev/build.sh -- dist-dependencies
    - run: ./dev/build.sh -- dist
    # - name: Sign artifacts
    #  run: |
    #    for i in dist/*; do
    #      gpg --verbose --local-user 1508E30E65C8C21F --output "$i".sig --detach-sig "$i"
    #    done
    - uses: actions/upload-artifact@v3
      with:
        name: elm-format-${{ github.sha }}-${{ matrix.build.archive-label }}
        path: dist/
