name: Build release

on:
  push:
    tags: '*'
    branches: 'release/*'

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: windows
            runner: windows-latest
            archive-label: Windows
          - name: macOS-x86
            runner: macOS-latest
            archive-label: macOS-x86

    name: release-${{ matrix.build.name }}
    runs-on: ${{ matrix.build.runner }}

    steps:
    - name: Configure environment
      run: |
        git config --global core.autocrlf false
    - name: Configure GPG Key
      run: |
        echo "$GPG_SIGNING_KEY" | base64 --decode > private.key
        gpg --import private.key
        rm private.key
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    - uses: actions/checkout@v3
    - uses: ./.github/actions/git-tags
    - uses: ./.github/actions/haskell
    - run: ./dev/build.sh -- dist-dependencies
    - run: ./dev/build.sh -- dist
    # - name: Sign artifacts
    #  run: |
    #    for i in dist/*; do
    #      gpg --verbose --local-user 1508E30E65C8C21F --output "$i".sig --detach-sig "$i"
    #    done
    - uses: actions/upload-artifact@v3
      with:
        name: elm-format-${{ github.sha }}-${{ matrix.build.archive-label }}
        path: dist/
