name: Build release (lamdera-community)

on:
  push:
    tags: '*'
    branches: 'release/*'

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
        - name: macOS-ARM64
          runner: [ self-hosted, macOS, ARM64 ]

    name: release-${{ matrix.build.name }}
    runs-on: ${{ matrix.build.runner }}

    steps:
    - name: Configure environment
      run: |
        git config --global core.autocrlf false
    - uses: actions/checkout@v3
    - name: Check platform
      run: |
        uname -m
        arch
        arch -arm64 uname -m
    - name: Workaround for https://github.com/actions/checkout/issues/290
      run: git fetch --tags --prune --unshallow --force
    - name: Clean x86 ghcup cache
      run: |
        rm -Rfv ~/.ghcup/ghc/9.2.5
        rm -Rfv ~/.ghcup/cabal/3.8.1.0
    - uses: haskell/actions/setup@v2
      name: Setup Haskell
      id: setup-haskell
      with:
        ghc-version: 9.2.5
    - name: Verify Haskell version
      run: |
        cabal --version
        ghc --version
        [[ $(ghc --numeric-version) == 9.2.5 ]]
        file "$(which cabal)"
        file "$(which ghc)"
    - uses: actions/cache@v3
      name: Cache cabal-release-v1-${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: cabal-release-v1-${{ runner.os }}-${{ hashFiles('cabal.project.freeze') }}
    - run: cabal v2-update
    - run: ./build.sh -- dist-dependencies
    - run: ./build.sh -- dist
    - uses: actions/upload-artifact@v3
      with:
        name: elm-format-${{ github.sha }}-${{ runner.os }}
        path: dist/
