name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        # - macOS-latest

    name: ci-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Configure environment
      run: |
        git config --global core.autocrlf false
    - uses: actions/checkout@v3
    - name: Workaround for https://github.com/actions/runner-images/issues/7061
      if: ${{ runner.os == 'Linux' }}
      run: sudo chown -R "$USER" /usr/local/.ghcup
    - uses: haskell/actions/setup@v2
      name: Setup Haskell
      id: setup-haskell
      with:
        ghc-version: 9.2.5
    - uses: actions/cache@v3
      name: Cache cabal-v3-${{ runner.os }}-${{ runner.arch }}
      with:
        path: ${{ steps.setup-haskell.outputs.cabal-store }}
        key: cabal-v3-${{ runner.os }}-${{ runner.arch }}
    - run: cabal v2-update
    - run: ./dev/build.sh -- dependencies
    - run: ./dev/build.sh -- build
    - name: Tests
      if: runner.os != 'Windows'
      run: |
        ./dev/build.sh
    - name: Tests (for Windows)
      if: runner.os == 'Windows'
      run: |
        ./dev/build.sh -- unit-tests
        echo "##[warning]integration tests are currently disabled on Windows CI"
