name: Snapshot release

on:
  push:
    branches:
      - 'json'
      - 'new-parser-2021'
      - 'snapshot/**'

defaults:
  run:
    shell: bash

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - macOS-latest
        # - windows-latest

    name: snapshot-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - name: Configure environment
      run: |
        git config --global core.autocrlf false
    - name: Configure SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SNAPSHOT_SSH_KEY }}
        known_hosts: ${{ secrets.SNAPSHOT_KNOWN_HOSTS }}
    - uses: actions/checkout@v3
    - uses: ./.github/actions/git-tags
    - uses: ./.github/actions/haskell
    - run: ./dev/build.sh -- dist-dependencies
    - run: ./dev/build.sh -- dist
    - name: Upload snapshot
      run: rsync -va dist/ "${{ secrets.SNAPSHOT_DEST }}/${BRANCH#refs/heads/}/$(git describe)/"
      env:
        BRANCH: ${{ github.ref }}
